package com.zombienw.onyxLib.blocks;

import java.util.List;

public interface BlockModel {

    String generateJson(String namespace);
    List<String> getTexturePaths();

    // Factory Methods
    static BlockModel armorStandStatic(String texturePath) {
        return new ArmorStandStatic(texturePath);
    }

    static BlockModel armorStandAllSides(String up, String down, String north, String east, String south, String west) {
        return new ArmorStandAllSides(up, down, north, east, south, west);
    }

    static BlockModel itemFrameStatic(String texturePath) {
        return new ItemFrameStatic(texturePath);
    }

    static BlockModel itemFrameAllSides(String up, String down, String north, String east, String south, String west) {
        return new ItemFrameAllSides(up, down, north, east, south, west);
    }

    // --- Shared Display Properties ---
    String ARMOR_STAND_DISPLAY = """
        "display": {
            "thirdperson_righthand": { "rotation": [0, -43.25, 0], "scale": [0.3, 0.3, 0.3] },
            "thirdperson_lefthand": { "rotation": [0, -43.25, 0], "scale": [0.3, 0.3, 0.3] },
            "firstperson_righthand": { "rotation": [0, -43.25, 0], "translation": [-0.5, 0.25, 0.5], "scale": [0.4, 0.4, 0.4] },
            "firstperson_lefthand": { "rotation": [0, -43.25, 0], "scale": [0.5, 0.5, 0.5] },
            "ground": { "scale": [0.3, 0.3, 0.3] },
            "gui": { "rotation": [30, 45, 0], "scale": [0.61, 0.6, 0.61] },
            "head": { "translation": [0, -13.375, 0], "scale": [2.15, 2.15, 2.15] },
            "fixed": { "scale": [0.6, 0.6, 0.6] }
        }""";

    String ITEM_FRAME_DISPLAY = """
        "display": {
            "gui": { "rotation": [30, -135, 0], "scale": [0.625, 0.625, 0.625] },
            "fixed": { "rotation": [0, 180, 0], "scale": [0.5, 0.5, 0.5] }
        }""";

    // --- Implementations ---

    record ArmorStandStatic(String texture) implements BlockModel {
        @Override
        public List<String> getTexturePaths() { return List.of(texture); }

        @Override
        public String generateJson(String namespace) {
            String texRef = namespace + ":" + texture;
            return """
                {
                    "credit": "Generated by OnyxLib",
                    "textures": {
                        "0": "%s",
                        "particle": "%s"
                    },
                    "elements": [
                        {
                            "from": [0, 0, 0],
                            "to": [16, 16, 16],
                            "faces": {
                                "north": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "east": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "south": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "west": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "up": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "down": {"uv": [0, 0, 16, 16], "texture": "#0"}
                            }
                        }
                    ],
                    %s
                }
                """.formatted(texRef, texRef, ARMOR_STAND_DISPLAY);
        }
    }

    record ArmorStandAllSides(String up, String down, String north, String east, String south, String west) implements BlockModel {
        @Override
        public List<String> getTexturePaths() {
            return List.of(up, down, north, east, south, west);
        }

        @Override
        public String generateJson(String namespace) {
            String u = namespace + ":" + up;
            String d = namespace + ":" + down;
            String n = namespace + ":" + north;
            String e = namespace + ":" + east;
            String s = namespace + ":" + south;
            String w = namespace + ":" + west;

            return """
                {
                    "credit": "Generated by OnyxLib",
                    "textures": {
                        "0": "%s",
                        "1": "%s",
                        "2": "%s",
                        "3": "%s",
                        "4": "%s",
                        "5": "%s",
                        "particle": "%s"
                    },
                    "elements": [
                        {
                            "from": [0, 0, 0],
                            "to": [16, 16, 16],
                            "faces": {
                                "up": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "down": {"uv": [0, 0, 16, 16], "texture": "#1"},
                                "north": {"uv": [0, 0, 16, 16], "texture": "#2"},
                                "east": {"uv": [0, 0, 16, 16], "texture": "#3"},
                                "south": {"uv": [0, 0, 16, 16], "texture": "#4"},
                                "west": {"uv": [0, 0, 16, 16], "texture": "#5"}
                            }
                        }
                    ],
                    %s
                }
                """.formatted(u, d, n, e, s, w, n, ARMOR_STAND_DISPLAY); // Using North as the particle texture
        }
    }

    record ItemFrameStatic(String texture) implements BlockModel {
        @Override
        public List<String> getTexturePaths() { return List.of(texture); }

        @Override
        public String generateJson(String namespace) {
            String texRef = namespace + ":" + texture;
            return """
                {
                    "credit": "Generated by OnyxLib",
                    "textures": { "0": "%s", "particle": "%s" },
                    "elements": [
                        {
                            "from": [0, 0, 0],
                            "to": [16, 16, 16],
                            "faces": {
                                "north": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "east": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "south": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "west": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "up": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "down": {"uv": [0, 0, 16, 16], "texture": "#0"}
                            }
                        }
                    ],
                    %s
                }
                """.formatted(texRef, texRef, ITEM_FRAME_DISPLAY);
        }
    }

    record ItemFrameAllSides(String up, String down, String north, String east, String south, String west) implements BlockModel {
        @Override
        public List<String> getTexturePaths() {
            return List.of(up, down, north, east, south, west);
        }

        @Override
        public String generateJson(String namespace) {
            String u = namespace + ":" + up;
            String d = namespace + ":" + down;
            String n = namespace + ":" + north;
            String e = namespace + ":" + east;
            String s = namespace + ":" + south;
            String w = namespace + ":" + west;

            return """
                {
                    "credit": "Generated by OnyxLib",
                    "textures": {
                        "0": "%s",
                        "1": "%s",
                        "2": "%s",
                        "3": "%s",
                        "4": "%s",
                        "5": "%s",
                        "particle": "%s"
                    },
                    "elements": [
                        {
                            "from": [0, 0, 0],
                            "to": [16, 16, 16],
                            "faces": {
                                "up": {"uv": [0, 0, 16, 16], "texture": "#0"},
                                "down": {"uv": [0, 0, 16, 16], "texture": "#1"},
                                "north": {"uv": [0, 0, 16, 16], "texture": "#2"},
                                "east": {"uv": [0, 0, 16, 16], "texture": "#3"},
                                "south": {"uv": [0, 0, 16, 16], "texture": "#4"},
                                "west": {"uv": [0, 0, 16, 16], "texture": "#5"}
                            }
                        }
                    ],
                    %s
                }
                """.formatted(u, d, n, e, s, w, n, ITEM_FRAME_DISPLAY); // North as particle texture
        }
    }
}