package com.zombienw.onyxlib.impl.pack;

import com.zombienw.onyxlib.impl.block.OnyxBlockDisplayImpl;
import com.zombienw.onyxlib.impl.block.OnyxBlockImpl;
import com.zombienw.onyxlib.impl.item.OnyxItemImpl;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generates item/block models and custom item model definitions.
 */
public class ModelGenerator {

    public void processItem(Path root, OnyxItemImpl item) throws IOException {
        String namespace = item.getKey().getNamespace();
        String id = item.getId();
        String targetModelPath = item.getCustomModelPath();

        if (targetModelPath == null && item.getTexturePath() != null) {
            targetModelPath = "item/" + id;
            Path modelDest = root.resolve("assets/" + namespace + "/models/" + targetModelPath + ".json");
            Files.createDirectories(modelDest.getParent());

            String modelJson = """
                {
                  "parent": "minecraft:item/generated",
                  "textures": {
                    "layer0": "%s:%s"
                  }
                }
                """.formatted(namespace, item.getTexturePath());

            Files.writeString(modelDest, modelJson);
        }

        if (targetModelPath != null) {
            createItemDefinitionJson(root, namespace, id, targetModelPath);
        }
    }

    public void processBlock(Path root, OnyxBlockImpl block) throws IOException {
        String namespace = block.getKey().getNamespace();
        String id = block.getId();
        String targetModelPath = block.getCustomModelPath();

        if (targetModelPath == null && block.getBlockDisplay() != null) {
            targetModelPath = "item/" + id;
            Path modelDest = root.resolve("assets/" + namespace + "/models/" + targetModelPath + ".json");
            Files.createDirectories(modelDest.getParent());

            Map<String, String> textures = ((OnyxBlockDisplayImpl) block.getBlockDisplay()).buildTextureMap();
            Files.writeString(modelDest, buildBlockModelJson(namespace, textures));
        }

        if (targetModelPath != null) {
            createItemDefinitionJson(root, namespace, id, targetModelPath);
        }
    }

    private void createItemDefinitionJson(Path root, String namespace, String id, String modelPath) throws IOException {
        Path defPath = root.resolve("assets/" + namespace + "/items/" + id + ".json");
        Files.createDirectories(defPath.getParent());

        String itemJson = """
            {
              "model": {
                "type": "minecraft:model",
                "model": "%s:%s"
              }
            }
            """.formatted(namespace, modelPath);

        Files.writeString(defPath, itemJson);
    }

    private String buildBlockModelJson(String namespace, Map<String, String> rawTextures) {
        List<String> textureLines = new ArrayList<>();
        List<String> faceLines = new ArrayList<>();
        String firstTexture = rawTextures.values().iterator().next();

        textureLines.add(String.format("        \"particle\": \"%s:%s\"", namespace, firstTexture));

        for (Map.Entry<String, String> entry : rawTextures.entrySet()) {
            String mcFace = entry.getKey().equalsIgnoreCase("top") ? "up" :
                    entry.getKey().equalsIgnoreCase("bottom") ? "down" :
                            entry.getKey().toLowerCase();

            String textureRef = namespace + ":" + entry.getValue();

            textureLines.add(String.format("        \"%s\": \"%s\"", mcFace, textureRef));
            faceLines.add(String.format("                \"%s\": { \"uv\": [0, 0, 16, 16], \"texture\": \"#%s\" }", mcFace, mcFace));
        }

        return getBlockModelTemplate(String.join(",\n", textureLines), String.join(",\n", faceLines));
    }

    private String getBlockModelTemplate(String texturesJson, String facesJson) {
        return """
            {
                "credit": "Generated by OnyxLib",
                "textures": {
            %s
                },
                "elements": [
                    {
                        "from": [0, 0, 0],
                        "to": [16, 16, 16],
                        "faces": {
            %s
                        }
                    }
                ],
                "display": {
                    "thirdperson_righthand": { "rotation": [75, 45, 0], "translation": [0, 2.5, 0], "scale": [0.375, 0.375, 0.375] },
                    "thirdperson_lefthand":  { "rotation": [75, 45, 0], "translation": [0, 2.5, 0], "scale": [0.375, 0.375, 0.375] },
                    "firstperson_righthand": { "rotation": [0, 45, 0], "scale": [0.4, 0.4, 0.4] },
                    "firstperson_lefthand":  { "rotation": [0, 225, 0], "scale": [0.4, 0.4, 0.4] },
                    "ground":                { "translation": [0, 3, 0], "scale": [0.25, 0.25, 0.25] },
                    "gui":                   { "rotation": [30, 225, 0], "scale": [0.625, 0.625, 0.625] },
                    "head":                  { "translation": [0, 0, 0], "scale": [1, 1, 1] },
                    "fixed":                 { "translation": [0, 0, 0], "scale": [1.0005, 1.0005, 1.0005] }
                }
            }
            """.formatted(texturesJson, facesJson);
    }
}