package com.zombienw.onyxlib.impl.pack;

import com.zombienw.onyxlib.OnyxPlugin;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

/**
 * Generates resource pack related metadata.
 */
public class PackMetaGenerator {

    private static final int PACK_FORMAT = 84;
    private static final int MAX_SUPPORTED_FORMAT = 108;
    private static final String PACK_DESCRIPTION = "Generated by OnyxLib";

    public void generate(OnyxPlugin plugin, Path rootDir) throws IOException {
        writeMcMeta(rootDir);
        writeIconImage(plugin, rootDir);
    }

    private void writeMcMeta(Path root) throws IOException {
        String mcmeta = """
            {
              "pack": {
                "pack_format": %d,
                "min_format": %d,
                "max_format": %d,
                "description": "%s"
              }
            }
            """.formatted(PACK_FORMAT, PACK_FORMAT, MAX_SUPPORTED_FORMAT, PACK_DESCRIPTION);

        Files.writeString(root.resolve("pack.mcmeta"), mcmeta, StandardCharsets.UTF_8);
    }

    private void writeIconImage(OnyxPlugin plugin, Path root) throws IOException {
        try (InputStream stream = plugin.getResource("icon.png")) {
            if (stream != null) {
                Files.copy(stream, root.resolve("pack.png"), StandardCopyOption.REPLACE_EXISTING);
            } else {
                plugin.getLogger().warning("icon.png missing from OnyxLib resources.");
            }
        }
    }
}