package com.zombienw.onyxlib.impl.pack;

import com.zombienw.onyxlib.OnyxPlugin;
import com.zombienw.onyxlib.impl.block.OnyxBlockDisplayImpl;
import com.zombienw.onyxlib.impl.block.OnyxBlockImpl;
import com.zombienw.onyxlib.impl.item.OnyxItemImpl;
import com.zombienw.onyxlib.impl.registry.NamespaceRegistry;
import com.zombienw.onyxlib.impl.registry.OnyxNamespaceImpl;
import org.bukkit.plugin.Plugin;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class PackGenerator {
    private static final int PACK_FORMAT = 84;
    private static final String PACK_DESCRIPTION = "Generated by OnyxLib";

    private final OnyxPlugin corePlugin;
    private final File outputFile;

    public PackGenerator(OnyxPlugin corePlugin) {
        this.corePlugin = corePlugin;
        this.outputFile = new File(corePlugin.getDataFolder(), "resourcepack.zip");
    }

    public String generate() throws IOException {
        List<OnyxItemImpl> assetItems = new ArrayList<>();
        List<OnyxBlockImpl> assetBlocks = new ArrayList<>();

        for (OnyxNamespaceImpl ns : NamespaceRegistry.getAllNamespaces()) {
            // Collect Items
            for (OnyxItemImpl item : ns.getItems()) {
                if (item.getTexturePath() != null) {
                    assetItems.add(item);
                }
            }

            // Collect Blocks
            for (OnyxBlockImpl block : ns.getBlocks()) {
                if (block.getBlockDisplay() != null) {
                    assetBlocks.add(block);
                }
            }
        }

        if (assetItems.isEmpty()) {
            return "No items with textures registered. Nothing to generate.";
        }

        Path tempDir = Files.createTempDirectory("onyxlib-pack-temp-");

        try {
            // Resource Pack Boilerplate
            writeMcMeta(tempDir);
            writeIconImage(tempDir);

            // Process Items
            writeItemTextures(tempDir, assetItems);
            writeItemModelFiles(tempDir, assetItems);
            writeItemDefinitions(tempDir, assetItems);

            // Process Blocks
            writeBlockTextures(tempDir, assetBlocks);
            writeBlockModelFiles(tempDir, assetBlocks);
            writeBlockItemDefinitions(tempDir, assetBlocks);

            zipDirectory(tempDir, outputFile.toPath());
        } finally {
            deleteDirectory(tempDir);
        }

        int totalAssets = assetItems.size() + assetBlocks.size();
        return "Resource pack generated: " + outputFile.getName() + " (" + totalAssets + " assets)";
    }

    private void writeMcMeta(Path root) throws IOException {
        String mcmeta = """
            {
              "pack": {
                "pack_format": %d,
                "description": "%s"
              }
            }
            """.formatted(PACK_FORMAT, PACK_DESCRIPTION);
        Files.writeString(root.resolve("pack.mcmeta"), mcmeta);
    }

    private void writeIconImage(Path root) throws IOException {
        InputStream stream = corePlugin.getResource("icon.png");
        if (stream == null) {
            corePlugin.getLogger().warning("icon.png missing from OnyxLib resources. Skipping icon.");
            return;
        }

        Path dest = root.resolve("pack.png");
        Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
    }

    // Item Generation

    private void writeItemTextures(Path root, List<OnyxItemImpl> items) throws IOException {
        for (OnyxItemImpl item : items) {
            String namespace = item.getKey().getNamespace();
            String texturePath = item.getTexturePath();
            copyTexture(root, namespace, texturePath);
        }
    }

    private void writeItemModelFiles(Path root, List<OnyxItemImpl> items) throws IOException {
        for (OnyxItemImpl item : items) {
            String namespace = item.getKey().getNamespace();
            String itemId = item.getId();
            Path modelDest = root.resolve("assets/" + namespace + "/models/item/" + itemId + ".json");
            Files.createDirectories(modelDest.getParent());

            String modelJson = """
                {
                  "parent": "minecraft:item/generated",
                  "textures": {
                    "layer0": "%s:%s"
                  }
                }
                """.formatted(namespace, item.getTexturePath());

            Files.writeString(modelDest, modelJson);
        }
    }

    private void writeItemDefinitions(Path root, List<OnyxItemImpl> items) throws IOException {
        for (OnyxItemImpl item : items) {
            createItemDefinitionJson(root, item.getKey().getNamespace(), item.getId());
        }
    }

    // Block Generation

    private void writeBlockTextures(Path root, List<OnyxBlockImpl> blocks) throws IOException {
        for (OnyxBlockImpl block : blocks) {
            String namespace = block.getKey().getNamespace();

            // get each texture
            Collection<String> texturePaths = new HashSet<>(((OnyxBlockDisplayImpl) block.getBlockDisplay()).buildTextureMap().values());
            for (String texturePath : texturePaths) {
                copyTexture(root, namespace, texturePath);
            }
        }
    }

    private void writeBlockModelFiles(Path root, List<OnyxBlockImpl> blocks) throws IOException {
        for (OnyxBlockImpl block : blocks) {
            String namespace = block.getKey().getNamespace();
            String blockId = block.getId();
            Path modelDest = root.resolve("assets/" + namespace + "/models/item/" + blockId + ".json");
            Files.createDirectories(modelDest.getParent());

            Map<String, String> rawTextures = ((OnyxBlockDisplayImpl) block.getBlockDisplay()).buildTextureMap();
            List<String> textureLines = new ArrayList<>();
            List<String> faceLines = new ArrayList<>();

            // Assign the first mapped texture as the block's particle texture
            String firstTexture = rawTextures.values().iterator().next();
            textureLines.add(String.format("        \"particle\": \"%s:%s\"", namespace, firstTexture));

            for (Map.Entry<String, String> entry : rawTextures.entrySet()) {
                String mcFace = mapToMinecraftFace(entry.getKey());
                String textureRef = namespace + ":" + entry.getValue();

                textureLines.add(String.format("        \"%s\": \"%s\"", mcFace, textureRef));
                faceLines.add(String.format("                \"%s\": { \"uv\": [0, 0, 16, 16], \"texture\": \"#%s\" }", mcFace, mcFace));
            }

            String texturesJson = String.join(",\n", textureLines);
            String facesJson = String.join(",\n", faceLines);

            String modelJson = getBlockModelTemplate(texturesJson, facesJson);
            Files.writeString(modelDest, modelJson);
        }
    }

    private void writeBlockItemDefinitions(Path root, List<OnyxBlockImpl> blocks) throws IOException {
        for (OnyxBlockImpl block : blocks) {
            createItemDefinitionJson(root, block.getKey().getNamespace(), block.getId());
        }
    }

    // Helpers

    private void copyTexture(Path root, String namespace, String texturePath) throws IOException {
        Plugin owningPlugin = NamespaceRegistry.getNamespace(namespace).getPlugin();
        String resourcePath = "assets/" + namespace + "/textures/" + texturePath + ".png";

        Path dest = root.resolve(resourcePath);
        if (Files.exists(dest)) return; // Skip if multiple blocks/items share the same texture

        InputStream stream = owningPlugin.getResource(resourcePath);
        if (stream == null) {
            throw new IOException("Missing texture in " + owningPlugin.getName() + " jar: " + resourcePath);
        }

        Files.createDirectories(dest.getParent());
        try (stream) {
            Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void createItemDefinitionJson(Path root, String namespace, String id) throws IOException {
        Path defPath = root.resolve("assets/" + namespace + "/items/" + id + ".json");
        Files.createDirectories(defPath.getParent());

        String itemJson = """
            {
              "model": {
                "type": "minecraft:model",
                "model": "%s:item/%s"
              }
            }
            """.formatted(namespace, id);

        Files.writeString(defPath, itemJson);
    }

    private String mapToMinecraftFace(String internalFace) {
        return switch (internalFace.toLowerCase()) {
            case "top" -> "up";
            case "bottom" -> "down";
            default -> internalFace.toLowerCase();
        };
    }

    private String getBlockModelTemplate(String texturesJson, String facesJson) {
        return """
            {
                "credit": "Generated by OnyxLib",
                "textures": {
            %s
                },
                "elements": [
                    {
                        "from": [0, 0, 0],
                        "to": [16, 16, 16],
                        "faces": {
            %s
                        }
                    }
                ],
                "display": {
                    "thirdperson_righthand": {
                        "rotation": [75, 45, 0],
                        "translation": [0, 2.5, 0],
                        "scale": [0.375, 0.375, 0.375]
                    },
                    "thirdperson_lefthand": {
                        "rotation": [75, 45, 0],
                        "translation": [0, 2.5, 0],
                        "scale": [0.375, 0.375, 0.375]
                    },
                    "firstperson_righthand": {
                        "rotation": [0, 45, 0],
                        "scale": [0.4, 0.4, 0.4]
                    },
                    "firstperson_lefthand": {
                        "rotation": [0, 225, 0],
                        "scale": [0.4, 0.4, 0.4]
                    },
                    "ground": {
                        "translation": [0, 3, 0],
                        "scale": [0.25, 0.25, 0.25]
                    },
                    "gui": {
                        "rotation": [30, 225, 0],
                        "scale": [0.625, 0.625, 0.625]
                    },
                    "head": {
                        "translation": [0, 0, 0],
                        "scale": [1, 1, 1]
                    },
                    "fixed": {
                        "translation": [0, 0, 0],
                        "scale": [1.0005, 1.0005, 1.0005]
                    }
                }
            }
            """.formatted(texturesJson, facesJson);
    }

    // zip temp directory into output file
    private void zipDirectory(Path source, Path destZip) throws IOException {
        Files.deleteIfExists(destZip);
        Files.createDirectories(destZip.getParent());

        try (ZipOutputStream zos = new ZipOutputStream(new BufferedOutputStream(Files.newOutputStream(destZip)))) {
            Files.walk(source).filter(p -> !Files.isDirectory(p)).forEach(p -> {
                ZipEntry zipEntry = new ZipEntry(source.relativize(p).toString().replace('\\', '/'));
                try {
                    zos.putNextEntry(zipEntry);
                    Files.copy(p, zos);
                    zos.closeEntry();
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            });
        }
    }

    private void deleteDirectory(Path dir) throws IOException {
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
        }
    }
}