package com.zombienw.onyxLib.core;

import com.zombienw.onyxLib.items.ItemAsset;
import com.zombienw.onyxLib.items.ItemService;
import com.zombienw.onyxLib.items.RegisteredItem;
import org.bukkit.Material;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class PackGenerator {
    private static final int PACK_FORMAT = 46;
    private static final String PACK_DESCRIPTION = "Generated by OnyxLib";

    private final ItemService itemService;
    private final File outputFile;
    private final JavaPlugin plugin;

    public PackGenerator(ItemService itemService, File onyxLibDataFolder, JavaPlugin plugin) {
        this.itemService = itemService;
        this.outputFile = new File(onyxLibDataFolder, "resourcepack.zip");
        this.plugin = plugin;
    }

    // Generates pack, returns summary
    public String generate() throws IOException {
        List<RegisteredItem> assetItems = itemService.all().stream()
                .filter(r -> r.getItem().hasAsset())
                .toList();

        if (assetItems.isEmpty()) {
            return "No items with assets are registered. Nothing to generate.";
        }

        Path tempDir = Files.createTempDirectory("onyxlib-pack-");

        try {
            writeMcMeta(tempDir);
            writeIconImage(tempDir);
            writeTextures(tempDir, assetItems);
            writeModelFiles(tempDir, assetItems);
            writeItemDefinitions(tempDir, assetItems);
            zipDirectory(tempDir, outputFile.toPath());
        } finally {
            deleteDirectory(tempDir);
        }

        return "Resource pack generated: " + outputFile.getPath()
                + " (" + assetItems.size() + " item(s))";
    }

    /// Writing/Building Files
    private void writeMcMeta(Path root) throws IOException {
        String mcmeta = """
            {
              "pack": {
                "pack_format": %d,
                "description": "%s"
              }
            }
            """.formatted(PACK_FORMAT, PACK_DESCRIPTION);

        Files.writeString(root.resolve("pack.mcmeta"), mcmeta);
    }

    private void writeIconImage(Path root) throws IOException {
        InputStream stream = plugin.getResource("icon.png");
        if (stream == null) {
            throw new IOException("Zach, how did you forget the icon.png");
        }

        Path dest = root.resolve("pack.png");
        Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
    }

    private void writeTextures(Path root, List<RegisteredItem> items) throws IOException {
        for (RegisteredItem registered : items) {
            ItemAsset asset = registered.getItem().getAsset();
            JavaPlugin owningPlugin = registered.getOwningPlugin();
            String namespace = registered.getNamespace();

            String resourcePath = "assets/" + namespace + "/textures/" + asset.getTexturePath() + ".png";

            InputStream stream = owningPlugin.getResource(resourcePath);
            if (stream == null) {
                throw new IOException("Missing texture in " + owningPlugin.getName() + " jar: " + resourcePath);
            }

            Path dest = root.resolve(resourcePath);
            Files.createDirectories(dest.getParent());
            try (stream) {
                Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

    /// Writes model JSON for each item under assets/namespace/models/item/id.json
    /// {
    ///     "parent": "item/generated",
    ///     "textures": { "layer0": "onyxtest:item/ruby" }
    /// }
    /// That sort of deal
    private void writeModelFiles(Path root, List<RegisteredItem> items) throws IOException {
        for (RegisteredItem registered : items) {
            ItemAsset asset = registered.getItem().getAsset();
            String namespace = registered.getNamespace();
            String itemId = registered.getItem().getId();

            Path modelDest = root.resolve("assets/" + namespace + "/models/item/" + itemId + ".json");
            Files.createDirectories(modelDest.getParent());

            if (asset.isCustomModel()) {
                copyModelFromJar(registered, modelDest);
            } else {
                generateModel(asset, namespace, modelDest);
            }
        }
    }
    private void copyModelFromJar(RegisteredItem registered, Path dest) throws IOException {
        JavaPlugin owningPlugin = registered.getOwningPlugin();
        String resourcePath = "assets/" + registered.getNamespace() + "/models/item/" + registered.getItem().getId() + ".json";

        try (InputStream stream = owningPlugin.getResource(resourcePath)) {
            if (stream == null) {
                throw new IOException("customModel() was set for '" + registered.getFullId()
                        + "' but no model file found in " + owningPlugin.getName() + " jar at: " + resourcePath);
            }
            Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void generateModel(ItemAsset asset, String namespace, Path dest) throws IOException {
        String textureRef = namespace + ":" + asset.getTexturePath();
        String modelJson = """
            {
              "parent": "minecraft:%s",
              "textures": {
                "layer0": "%s"
              }
            }
            """.formatted(asset.getModelParent(), textureRef);
        Files.writeString(dest, modelJson);
    }


    /// I fucking hate all of this
    /// Writes an item definition JSON under assets/minecraft/items/material.json
    /// This is a new thing as part of the new custom model data system
    /// range_dispatch switches models
    /// each item has one threshold entry. vanilla model is fallback
    ///
    /// example: assets/minecraft/items/iron_nugget.json
    /// {
    ///     "model": {
    ///         "type": "minecraft:range_dispatch",
    ///         "property": "minecraft:custom_model_data",
    ///         "fallback": { "type": "minecraft:model", "model": "minecraft:item/iron_nugget" },
    ///         "entries": [
    ///             { "threshold": 1.0, "model": { "type": "minecraft:model", "model": "onyxtest:item/ruby" } }
    ///         ]
    ///     }
    /// }
    private void writeItemDefinitions(Path root, List<RegisteredItem> items) throws IOException {
        Map<Material, List<RegisteredItem>> byMaterial = items.stream()
                .collect(Collectors.groupingBy(r -> r.getItem().getMaterial()));

        for (var entry : byMaterial.entrySet()) {
            String materialKey = entry.getKey().getKey().getKey();
            List<RegisteredItem> group = entry.getValue();
            group.sort(Comparator.comparing(RegisteredItem::getFullId));

            Path defPath = root.resolve("assets/minecraft/items/" + materialKey + ".json");
            Files.createDirectories(defPath.getParent());
            Files.writeString(defPath, buildItemDefinitionJson(materialKey, group));
        }
    }

    private String buildItemDefinitionJson(String materialKey, List<RegisteredItem> items) {
        StringBuilder cases = new StringBuilder();

        for (int i = 0; i < items.size(); i++) {
            RegisteredItem registered = items.get(i);
            String modelRef = registered.getNamespace() + ":item/" + registered.getItem().getId();

            cases.append("        {\n")
                    .append("          \"when\": \"").append(modelRef).append("\",\n")
                    .append("          \"model\": { \"type\": \"minecraft:model\", \"model\": \"").append(modelRef).append("\" }\n")
                    .append("        }");

            if (i < items.size() - 1) cases.append(",");
            cases.append("\n");
        }

        return """
            {
              "model": {
                "type": "minecraft:select",
                "property": "minecraft:custom_model_data",
                "index": 0,
                "fallback": {
                  "type": "minecraft:model",
                  "model": "minecraft:item/%s"
                },
                "cases": [
            %s    ]
              }
            }
            """.formatted(materialKey, cases.toString());
    }

    /// Zip & Cleanup
    // Why the fuck are java file operations so hard
    private void zipDirectory(Path source, Path destZip) throws IOException {
        Files.deleteIfExists(destZip);
        Files.createDirectories(destZip.getParent());

        try (ZipOutputStream zos = new ZipOutputStream(new BufferedOutputStream(Files.newOutputStream(destZip)))) {

            Files.walk(source).filter(p -> !Files.isDirectory(p)).forEach(p -> {

                ZipEntry zipEntry = new ZipEntry(source.relativize(p).toString().replace('\\', '/'));
                try {
                    zos.putNextEntry(zipEntry);
                    Files.copy(p, zos);
                    zos.closeEntry();
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            });
        }
    }

    private void deleteDirectory(Path dir) throws IOException {
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
        }
    }
}
