package com.zombienw.onyxLib.core;

import com.zombienw.onyxLib.items.ItemAsset;
import com.zombienw.onyxLib.items.ItemService;
import com.zombienw.onyxLib.items.RegisteredItem;
import org.bukkit.Material;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class PackGenerator {
    private static final int PACK_FORMAT = 46;
    private static final String PACK_DESCRIPTION = "Generated by OnyxLib";

    private final ItemService itemService;
    private final File outputFile;
    private final JavaPlugin plugin;

    public PackGenerator(ItemService itemService, File onyxLibDataFolder, JavaPlugin plugin) {
        this.itemService = itemService;
        this.outputFile = new File(onyxLibDataFolder, "resourcepack.zip");
        this.plugin = plugin;
    }

    // Generates pack, returns summary
    public String generate() throws IOException {
        List<RegisteredItem> assetItems = itemService.all().stream()
                .filter(r -> r.getItem().hasAsset())
                .toList();

        if (assetItems.isEmpty()) {
            return "No items with assets are registered. Nothing to generate.";
        }

        Path tempDir = Files.createTempDirectory("onyxlib-pack-");

        try {
            writeMcMeta(tempDir);
            writeIconImage(tempDir);
            writeTextures(tempDir, assetItems);
            writeModelFiles(tempDir, assetItems);
            writeItemDefinitions(tempDir, assetItems);
            zipDirectory(tempDir, outputFile.toPath());
        } finally {
            deleteDirectory(tempDir);
        }

        return "Resource pack generated: " + outputFile.getPath()
                + " (" + assetItems.size() + " item(s))";
    }

    /// Writing/Building Files
    private void writeMcMeta(Path root) throws IOException {
        String mcmeta = """
            {
              "pack": {
                "pack_format": %d,
                "description": "%s"
              }
            }
            """.formatted(PACK_FORMAT, PACK_DESCRIPTION);

        Files.writeString(root.resolve("pack.mcmeta"), mcmeta);
    }

    private void writeIconImage(Path root) throws IOException {
        InputStream stream = plugin.getResource("icon.png");
        Path dest = root.resolve("pack.png");
        if (stream == null) {
            throw new IOException("Zach, how did you forget the icon.png");
        }
        Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
    }

    private void writeTextures(Path root, List<RegisteredItem> items) throws IOException {
        for (RegisteredItem registered : items) {
            ItemAsset asset = registered.getItem().getAsset();
            JavaPlugin plugin = registered.getOwningPlugin();
            String namespace = registered.getNamespace();

            // assets/onyxtest/textures/item/ruby.png
            String resourcePath = "assets/" + namespace + "/textures/" + asset.getTexturePath() + ".png";

            InputStream stream = plugin.getResource(resourcePath);
            if (stream == null) {
                throw new IOException("Missing texture in " + plugin.getName()
                        + " jar: " + resourcePath);
            }

            Path dest = root.resolve(resourcePath);
            Files.createDirectories(dest.getParent());
            try (stream) {
                Files.copy(stream, dest, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

    /// Writes model JSON for each item under assets/namespace/models/item/id.json
    /// {
    ///     "parent": "item/generated",
    ///     "textures": { "layer0": "onyxtest:item/ruby" }
    /// }
    /// That sort of deal
    private void writeModelFiles(Path root, List<RegisteredItem> items) throws IOException {
        for (RegisteredItem registered : items) {
            ItemAsset asset = registered.getItem().getAsset();
            String namespace = registered.getNamespace();
            String itemId = registered.getItem().getId();

            // namespace:item/texturename (no .png suffix)
            String textureRef = namespace + ":" + asset.getTexturePath();

            String modelJson = """
                    {
                      "parent": "%s",
                      "textures": {
                        "layer0": "%s"
                      }
                    }
                    """.formatted(asset.getModelParent(), textureRef);

            // assets/<namespace>/models/item/<id>.json
            Path modelPath = root.resolve("assets/" + namespace + "/models/item/" + itemId + ".json");
            Files.createDirectories(modelPath.getParent());
            Files.writeString(modelPath, modelJson);
        }
    }

    /// I fucking hate all of this
    /// Writes an item definition JSON under assets/minecraft/items/material.json
    /// This is a new thing as part of the new custom model data system
    /// range_dispatch switches models
    /// each item has one threshold entry. vanilla model is fallback
    ///
    /// example: assets/minecraft/items/iron_nugget.json
    /// {
    ///     "model": {
    ///         "type": "minecraft:range_dispatch",
    ///         "property": "minecraft:custom_model_data",
    ///         "fallback": { "type": "minecraft:model", "model": "minecraft:item/iron_nugget" },
    ///         "entries": [
    ///             { "threshold": 1.0, "model": { "type": "minecraft:model", "model": "onyxtest:item/ruby" } }
    ///         ]
    ///     }
    /// }
    private void writeItemDefinitions(Path root, List<RegisteredItem> items) throws IOException {
        Map<Material, List<RegisteredItem>> byMaterial = items.stream()
                .collect(Collectors.groupingBy(r -> r.getItem().getMaterial()));

        for (var entry : byMaterial.entrySet()) {
            String materialKey = entry.getKey().getKey().getKey(); // e.g. "iron_nugget"
            List<RegisteredItem> group = entry.getValue();
            group.sort(Comparator.comparingInt(RegisteredItem::getAssignedCmd));

            String itemDefJson = buildItemDefinitionJson(materialKey, group);

            // assets/minecraft/items/<material>.json  (note: items/, not models/item/)
            Path defPath = root.resolve("assets/minecraft/items/" + materialKey + ".json");
            Files.createDirectories(defPath.getParent());
            Files.writeString(defPath, itemDefJson);
        }
    }

    private String buildItemDefinitionJson(String materialKey, List<RegisteredItem> items) {
        StringBuilder entries = new StringBuilder();

        for (int i = 0; i < items.size(); i++) {
            RegisteredItem registered = items.get(i);
            String namespace = registered.getNamespace();
            String itemId = registered.getItem().getId();

            // threshold is the float value stored in the custom_model_data component
            float threshold = (float) registered.getAssignedCmd();

            // Model reference points to our generated model file
            String modelRef = namespace + ":item/" + itemId;

            entries.append("        {\n")
                    .append("          \"threshold\": ").append(threshold).append(",\n")
                    .append("          \"model\": { \"type\": \"minecraft:model\", \"model\": \"").append(modelRef).append("\" }\n")
                    .append("        }");

            if (i < items.size() - 1) entries.append(",");
            entries.append("\n");
        }

        return """
                {
                  "model": {
                    "type": "minecraft:range_dispatch",
                    "property": "minecraft:custom_model_data",
                    "fallback": { "type": "minecraft:model", "model": "minecraft:item/%s" },
                    "entries": [
                %s    ]
                  }
                }
                """.formatted(materialKey, entries);
    }

    /// Zip & Cleanup
    // Why the fuck are java file operations so hard
    private void zipDirectory(Path source, Path destZip) throws IOException {
        Files.deleteIfExists(destZip);
        Files.createDirectories(destZip.getParent());

        try (ZipOutputStream zos = new ZipOutputStream(new BufferedOutputStream(Files.newOutputStream(destZip)))) {

            Files.walk(source).filter(p -> !Files.isDirectory(p)).forEach(p -> {

                ZipEntry zipEntry = new ZipEntry(source.relativize(p).toString().replace('\\', '/'));
                try {
                    zos.putNextEntry(zipEntry);
                    Files.copy(p, zos);
                    zos.closeEntry();
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            });
        }
    }

    private void deleteDirectory(Path dir) throws IOException {
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
        }
    }
}
