/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    introSidebar: [{type: 'autogenerated', dirName: '.'}],
    gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
